### ISSUE TITLE
App crashes on "Secret is not set"

### ISSUE THREAD

**Issue by nlamah** [parley-messaging/ios-library#148]
**Describe the Bug**
Version 4.1.8 contained the following fix: `Fixed an issue that could cause a crash when entering foreground after resetting due to the registered observers.`
Unfortunately this is still happening.
One think that would be preferable is that the app does not crash, but gives the app the possibility to handle the error, by showing an alert, for example.

**To Reproduce**
* In the example app, in AppDelegate in the function `applicationWillEnterForeground` add the following snippet 
`DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
            Parley.purgeLocalMemory()
        }`
* Build the app
* Press the 'Start Chat' button
* Bring the app to the background
* Bring the app to the foreground
* Wait a little bit
* The app crashes on the line about the secret: https://github.com/parley-messaging/ios-library/blob/master/Sources/Parley/Data/Remotes/ParleyRemote.swift#L37C39-L37C56

**Expected behaviour**
* Prevent that createHeaders is called without a set secret.
* Prevent to make the app crash when the situation occurs.

**Screenshots**
<img width="917" alt="Screenshot 2024-07-30 at 14 34 43" src="https://github.com/user-attachments/assets/7c3f8242-f63c-4ab1-b1bd-050e61e7432e">

**Comment by alexkok** [comment]
Thanks for the report. Investigated: 

The issue originates from the `willEnterForeground` which Parley executes the configure on (causing the network call to be done without having the secret set). 

The recent change where purging the memory sets the state to `unconfigured` caused this effect. However, purgeLocalMemory also removes the observers where this should be prevented. So that is good.

Thanks for the reproduce, although it's explanatory how that happens in that case: The observer is triggered, configure is being called, and only after 0.1sec the observer is removed, but at that time the observer was already called.

I've two findings about this (`removeObservers` is wrong), that fix we'll apply in the next version (which should solve this issue at its core).
However, the suggested change does no harm, and is neater than fatal erroring. So we'll merge that as well, thanks! 👍

**Comment by alexkok** [comment]
Fixed and released in [4.2.0](https://github.com/parley-messaging/ios-library/releases/tag/4.2.0) 🚀
