### ISSUE TITLE
Notification issue with new button types

### ISSUE THREAD

**Issue by rubenaalders** [parley-messaging/ios-library#36]
Hi! 

I've encountered a 'new' issue after upgrading to the latest SDK version. Those new button types (buttons, carrousel) do work on Android, but we can't get them working on iOS when there is a new message and push that to the `Parley.handle()` method after receiving it in a notification. In previous versions it didn't work at all. In the latest version the message is shown, but the buttons for it never show. On Android the message is first shown and then the buttons are shown after a small delay. This makes me suspect the buttons are loaded by the SDK based on the message ID?

A small side issue is that the buttons do not fit on the latest build.

I've included screenshots and examples for both.

Android: 
`Bundle[{google.delivered_priority=normal, google.sent_time=1674047960692, google.ttl=2419200, google.original_priority=normal, parley={"type":"message","object":{"id":48967777,"typeId":2,"title":null,"body":"goedemorgen, heb je nog geshopt in de WHD?"}}, typeId=2, id=48967777, from=755622197466, time=1674047960, topic=CHAT, google.message_id=0:1674047960711681%edd8b661f9fd7ecd, message=goedemorgen, heb je nog geshopt in de WHD?, google.c.sender.id=755622197466}]`

iOS: `{"Token":"f5sW4Att606oiG0JFxahPO:APA91bH4sYcIBDVTmKfspwAkU1gX8mEPCCd5mh01lURtKXDUXpgwNorUnCj1fZFyCWdZOyaxEPaIEKUKeUDRXFrnEdv62amowu2hYLvwqcbyFwyTaO73eRJZqfNL7-kmn38GT7rTrzAq","Topic":null,"Condition":null,"Data":{"parley":"{\u0022type\u0022:\u0022message\u0022,\u0022object\u0022:{\u0022id\u0022:48967777,\u0022typeId\u0022:2,\u0022title\u0022:null,\u0022body\u0022:\u0022goedemorgen, heb je nog geshopt in de WHD?\u0022}}","id":"48967777","message":"goedemorgen, heb je nog geshopt in de WHD?","time":"1674047960","typeId":"2","topic":"CHAT"},"Notification":{"Title":null,"Body":"goedemorgen, heb je nog geshopt in de WHD?","ImageUrl":null},"Android":null,"Webpush":null,"Apns":{"Headers":null,"FcmOptions":null,"Aps":{"Alert":null,"AlertString":null,"Badge":null,"Sound":null,"CriticalSound":null,"ContentAvailable":false,"MutableContent":true,"Category":null,"ThreadId":null,"CustomData":null},"CustomData":null},"FcmOptions":null}`

![simulator_screenshot_673F1261-EA7E-4216-9B5A-BB774042CC44](https://user-images.githubusercontent.com/4243098/213186562-95509805-353a-42a2-80c6-3b22f54f9288.png)

**Comment by alexkok** [comment]
Thanks for reporting @rubenaalders , we will look into it!

**Comment by alexkok** [comment]
Hi @rubenaalders , can you check out version 3.6.2? We have applied some fixes with the quick replies, buttons and carousels in there which you were facing as well. Also the buttons now properly show up with the desired width again (configurable in the `ParleyAppearance`).

Additionally, some more info related to how the chat works:

- The data given from the logs is only about the first message that you receive. Thanks for providing them!
- The quick replies is (yet another) received message, so you'll receive 2 notifications that should be given to the `Parley.handle()` method (I assume this works just fine) -- Likely the small delay of showing the quick replies on Android is because it gets send or received slightly later than the first message.
- To get the naming right:
  - Buttons are those inside the message (seen as `Wehkamp Website` on your screenshot)
  - Quick replies are those at the bottom of the screen (seen as `ja`, `nee`, and `weet niet` in your screenshot)
- Quick replies vanish once a new message is there

**Comment by rubenaalders** [comment]
Hi @alexkok, thanks for the quick work. I can indeed confirm that 3.6.2 fixes the look of the quick reply buttons. The notifications not working was combination of not expecting it to be 2 notifications and the iOS SDK having guards at the handle function for stuff that seems unnecessary, like the body. So we now also always pass an empty body and it seems to work :).

**Comment by alexkok** [comment]
Great! Thanks for confirming 👍 

Nice catch about the notifications. Parley definitely uses notifications without body yes. Also Parley won't do anything with notifications that were not meant for Parley. 

As additional info (see source: https://github.com/parley-messaging/ios-library/blob/master/Source/Parley.swift#L467):
The `handle()` function returns a boolean that indicates whether the notification was handled by Parley or not. So you could use that as indicator instead of guarding. Or if you really want to guard around the `handle()` method, I would recommend putting a guard based on whether the notification contains the `parley` key. As this key is the very base of all notifications of Parley.

**Comment by rubenaalders** [comment]
Thanks for the info. I think I didn't express myself correctly. What I meant is that these guards: 
https://github.com/parley-messaging/ios-library/blob/f6531a5d7e17ca2c567d7e7516bfd9661ca62865/Source/Parley.swift#L362 
Made our life harder than it should have been.

**Comment by alexkok** [comment]
Oh I see, while `Message.message` is in fact nullable 🤔  -- We should look into the reasoning of that statement, I'll take a note of this one to review it sometime later.

Thanks!
