### ISSUE TITLE
Correct seperation of `ParleyNetworkSession`

### ISSUE THREAD

**Issue by mat1th** [parley-messaging/ios-library#77]
**Describe the feature**
I've created a way of abstracting the network layer with introducing a `ParleyNetworkSession` protocol in https://github.com/parley-messaging/ios-library/pull/58. While implementing this in our own code base I did find some issues in my implementation. 
- The protocol did have a `parameters: [String: Any]?` parameter. Those parameters should sometimes be part of the URL (`GET`, `HEAD` and `DELETE`). And sometimes they should be part of the body. I actually think this logic should be part of the Parley SDK itself and not part of the implementation of `ParleyNetworkSession`.
- When the `parameters: [String: Any]?` need to be part of the body they are encoded in Alamofire itself. See https://github.com/Alamofire/Alamofire/blob/5.8.1/Source/ParameterEncoder.swift#L174. When I want to implement `ParleyNetworkSession` I need to know that 
    1. The `parameters: [String: Any]?` need to be part of the body. 
    2. The `parameters: [String: Any]?,` need to be `x-www-form-urlencoded`. I do not think this should be done by the implementer of `ParleyNetworkSession`. 

What are your thoughts on this, and are you open for a PR that will move the logic of the `parameters: [String: Any]?` away from the `ParleyNetworkSession` and implement this in the Parley SDK itself? This means that I need to create a way to make a `x-www-form-urlencoded` from in the SDK. Does your api also support sending JSON objects. That would be a lot easier to implement.

A possible solution could be https://github.com/parley-messaging/ios-library/compare/master...mat1th:parley-ios-library:feature/improve-ParleyNetworkSession-protocol?expand=1

**Comment by alexkok** [comment]
Thanks for reporting @mat1th and clearly describing the issue. Needing to have the knowledge how to implement the body is indeed not very clear currently, while it should be clear when implementing `ParleyNetworkSession`.

Yes, we are open for PR's for sure! Thanks for the provided changes as a head start to review and proceed on.

It would be great to remove, or improve, the way how we send parameters:

- A concern I could think of is that if we ever need query parameters, we might want to have an option to send parameters and a body. However, we don't need query params currently, so we don't need to support that yet either ✅ 
- That said, we should rename parameters here to `body` for sure, since currently this value is intended as the body of the request (which is what you've already done in the suggested changes) ✅

About the implementation:

1. Correct, Alamofire uses `x-www-form-urlencoded` by default. The Parley API supports json yes, we also use that on Android actually. Let's move to `application/json` instead as body content type.
2. In the suggested changes, sending the body is done by relying on the `upload` method of the `ParleyNetworkSession`. I think this won't work correctly? Since the `upload` method is intended for the multipart upload (uploading images/media) which likely needs different handling. So making that one always having the content type form-urlencoded will probably break the media upload. Must say that I didn't test these suggested changes yet, more a concern that came up when reviewing. Point 3 bellow will handle this anyway:
3. We should test and verify, but we can likely put the Content Type header to `application/json` always when sending body data. I guess we could then attach the body to the `request` method, and just put the content type header always as `application/json`. Since only the `upload` method will have an other content type (multipart).

**Comment by mat1th** [comment]
I've created a pr with your suggestions see https://github.com/parley-messaging/ios-library/pull/78.

**Comment by alexkok** [comment]
Resolved & released in [4.0.1](https://github.com/parley-messaging/ios-library/releases/tag/4.0.1) 🚀
